{
 "title": "Monitoring AKS Resources",
 "description": "Kubernetes Unavailable list (master,worker)\r\nKubernetes cluster cpu,mem (util,req,limits)\r\nLast not running pod Iist (by time)\r\nKubernetes Cluster cpu util by namespace and node\r\nKubernetes Cluster mem util by namespace and node\r\nTop cpu used pods,\r\nTop mem used pods,\r\nPortworx volume usage (label replace; pvcname - namespace)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "origin_prometheus",
    "query": {
     "query": "label_values(kube_node_info,origin_prometheus)"
    }
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "k8s_cluster",
    "query": {
     "query": "label_values(kube_node_info,cluster)"
    }
   },
   {
    "name": "k8s_nodes",
    "query": {
     "query": "label_values(kube_node_info{origin_prometheus=~\"$origin_prometheus\", cluster=\"$k8s_cluster\"},node)"
    }
   },
   {
    "name": "k8s_namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$k8s_cluster\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Node Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=\"$k8s_nodes\", cluster=\"$k8s_cluster\"} - node_memory_MemAvailable_bytes{instance=\"$k8s_nodes\", cluster=\"$k8s_cluster\"}) / sum(node_memory_MemTotal_bytes{instance=\"$k8s_nodes\", cluster=\"$k8s_cluster\"})"
    }
   ]
  },
  {
   "title": "CPU  Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum by (cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\", instance=\"$k8s_nodes\", cluster=\"$k8s_cluster\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$k8s_nodes\", cluster=\"$k8s_cluster\"} - node_boot_time_seconds{instance=\"$k8s_nodes\", cluster=\"$k8s_cluster\"}"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=\"$k8s_nodes\", cluster=\"$k8s_cluster\"} - node_memory_MemAvailable_bytes{instance=\"$k8s_nodes\", cluster=\"$k8s_cluster\"})"
    }
   ]
  },
  {
   "title": "Pods on node",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{node=\"$k8s_nodes\", cluster=\"$k8s_cluster\"})"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\", instance=\"$k8s_nodes\", cluster=\"$k8s_cluster\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$k8s_nodes\"} - node_memory_MemFree_bytes{instance=\"$k8s_nodes\"} - node_memory_Buffers_bytes{instance=\"$k8s_nodes\"} - node_memory_Cached_bytes{instance=\"$k8s_nodes\"}",
     "legendFormat": "memory used"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"$k8s_nodes\"}",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$k8s_nodes\"}",
     "legendFormat": "memory cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$k8s_nodes\"}",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=\"$k8s_nodes\", cluster=\"$k8s_cluster\"}[$__rate_interval]) * 100) by (mode)",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Network usage (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{instance=\"$k8s_nodes\", cluster=\"$k8s_cluster\"}[$__rate_interval]))",
     "legendFormat": "In"
    },
    {
     "expr": "- sum(rate(node_network_transmit_bytes_total{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Memory Utilization by NODE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\", cluster=\"$k8s_cluster\"}) by (instance)",
     "legendFormat": "{{ node}}"
    }
   ]
  },
  { "title": "Kubernetes Namespace Cpu - Mem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "CPU Utilization by namespace",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", cluster=\"$k8s_cluster\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Memory Utilization by namespace",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\", cluster=\"$k8s_cluster\"}) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Kubernetes Cpu - Mem Usage of Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 }
  },
  {
   "title": "CPU Usage (milicores)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "1000 * sum by (pod, container) (\r\n  irate(container_cpu_usage_seconds_total{namespace=~\"$k8s_namespace\", cluster=\"$k8s_cluster\", container!=\"\"}[1m])\r\n)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "label_replace(\r\n  kube_pod_container_info{namespace=\"${k8s_namespace}\"},\r\n  \"container_id_trimmed\", \"$1\",\r\n  \"container_id\", \"^(?:docker|containerd)://(.*)$\"\r\n)\r\n* on(container_id_trimmed) group_left()\r\n(\r\n  avg by (container_id_trimmed) (\r\n    label_replace(\r\n      rate(windows_container_cpu_usage_seconds_total[1m]),\r\n      \"container_id_trimmed\", \"$1\",\r\n      \"container_id\", \"^(?:docker|containerd)://(.*)$\"\r\n    )\r\n  ) * 1000\r\n)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\", namespace=\"$k8s_namespace\", cluster=\"$k8s_cluster\"}) by (namespace, pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "label_replace(\r\n  kube_pod_container_info{namespace=\"${k8s_namespace}\"},\r\n  \"container_id_trimmed\", \"$1\",\r\n  \"container_id\", \"^(?:docker|containerd)://(.*)$\"\r\n)\r\n* on(container_id_trimmed) group_left()\r\n(\r\n  avg by (container_id_trimmed) (\r\n    label_replace(\r\n      rate(windows_container_cpu_usage_seconds_total[1m]),\r\n      \"container_id_trimmed\", \"$1\",\r\n      \"container_id\", \"^(?:docker|containerd)://(.*)$\"\r\n    )\r\n  ) * 1000\r\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}