global:
  resolve_timeout: 1m

route:
  group_by: [ "alertname" ]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: "alert_channel"

  routes:
  - match:
      severity: warning
    receiver: 'alert_channel'
    group_wait: 30s
    group_interval: 3m
    # active_time_intervals:
    # - workhours

  - match:
      severity: error
    receiver: 'alert_channel'
    group_wait: 10s
    group_interval: 5m
    repeat_interval: 1h
    # active_time_intervals:
    # - workhours

  - match:
      severity: critical
    receiver: 'alert_channel'
    group_wait: 10s
    group_interval: 5m
    repeat_interval: 30m
    # active_time_intervals:
    # - workhours

receivers:
- name: alert_channel
  webhook_configs:
  - url: 'http://prometheus-msteams:2000/url'
    send_resolved: true

# - name: workhours
#   time_intervals:
#   - weekdays: [ "monday:friday" ]
#     location: Asia/Ho_Chi_Minh
#     times:
#     - start_time: "08:00"
#       end_time: "18:00"
#   - weekdays: [ "saturday" ]
#     location: Asia/Ho_Chi_Minh
#     times:
#     - start_time: "08:00"
#       end_time: "12:00"
