############# Define Rule Alert ###############
groups:
- name: Linux-alert
  rules:
  ################ Linux High CPU Usage
  - alert: Linux High CPU Usage
    expr: 100 - avg(irate(node_cpu_seconds_total{mode="idle"}[2m])) by (instance) * 100 > 70
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Linux High CPU Usage ({{ $labels.instance }}) for 5m"
      description: "CPU Usage is more than 70%"
      value: "{{ $value }}"
  ################ Linux High Memory Usage
  - alert: Linux High Memory Usage
    expr: (node_memory_Memtotal_bytes - (node_memory_MemFree_bytes + node_memory_Cached_bytes + node_memory_Buffers_bytes)) / node_memory_MemTotal_bytes * 100 > 70
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Linux High Memory Usage ({{ $labels.instance }}) for 5m"
      description: "Memory Usage is more than 70%"
      value: "{{ $value }}"
  ################ Linux Low Disk Space
  - alert: Linux Low Disk Space
    expr: 100 - (node_filesystem_avail_bytes{mountpoint="/"}) / node_filesystem_size_bytes{mountpoint="/"} * 100 > 70
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Linux Low Disk Space ({{ $labels.instance }})"
      description: "Disk Space is used more than 70%"
      value: "{{ $value }}"
  ################ Linux Node Down
  - alert: Linux Node Down
    expr: up{job="linux-exporters"} == 0
    for: 10m
    labels:
      severity: critical
    annotations:
      summary: "Linux Node Down ({{ $labels.instance }})"
      description: "The Linux node is down for more than 5 minutes"
